
spring:
  thymeleaf:
    cache: false
    prefix: src/main/resources/templates/ # jar 배포시에는 spring.thymeleaf.prefix 항목을 주석처리
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/sbb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
#        show_sql: true // System.out에 출력
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.mysite.sbb.configuration.CamelCaseToSnakeAndUpperCaseStrategy