
spring:
  config:
    activate:
      on-profile: profile2
  datasource:
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
