

spring:
  config:
    activate:
      on-profile: profile1
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/sbb3
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA
  jpa:
    hibernate:
      ddl-auto: update