-- STEP 1 키워드 분기: SELECT q.* (8/8 기존) vs SELECT q.ID (8/9 변경) 실행계획 비교
SELECT '=== SELECT q.* (legacy) ===' AS marker;
EXPLAIN
SELECT q.* FROM QUESTION q WHERE q.ID IN (
  SELECT q2.ID FROM QUESTION q2
   WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
  UNION
  SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID
   WHERE u1.USERNAME LIKE '%자바%'
  UNION
  SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID
   WHERE u2.USERNAME LIKE '%자바%'
) ORDER BY q.CREATE_DATE DESC LIMIT 10;

SELECT '=== SELECT q.ID (current) ===' AS marker;
EXPLAIN
SELECT q.ID FROM QUESTION q WHERE q.ID IN (
  SELECT q2.ID FROM QUESTION q2
   WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
  UNION
  SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID
   WHERE u1.USERNAME LIKE '%자바%'
  UNION
  SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID
   WHERE u2.USERNAME LIKE '%자바%'
) ORDER BY q.CREATE_DATE DESC LIMIT 10;
