-- 키워드 검색 STEP 1: IN (서브쿼리) vs JOIN (파생 테이블) 실행계획 비교
-- 목적: DEPENDENT SUBQUERY / DEPENDENT UNION 이 사라지는지 확인
-- 사용: docker exec -i sbb-performance-test-db mysql -usbbtest -ptest1234 sbb_db < explain-kw-join.sql

SELECT '=== A. 현재: IN (subquery) ===' AS marker;
EXPLAIN
SELECT q.ID FROM QUESTION q WHERE q.ID IN (
  SELECT q2.ID FROM QUESTION q2
   WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
  UNION
  SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID
   WHERE u1.USERNAME LIKE '%자바%'
  UNION
  SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID
   WHERE u2.USERNAME LIKE '%자바%'
) ORDER BY q.CREATE_DATE DESC LIMIT 10;

SELECT '=== B. 제안: JOIN (derived table) ===' AS marker;
EXPLAIN
SELECT q.ID FROM QUESTION q JOIN (
  SELECT q2.ID AS ID FROM QUESTION q2
   WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
  UNION
  SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID
   WHERE u1.USERNAME LIKE '%자바%'
  UNION
  SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID
   WHERE u2.USERNAME LIKE '%자바%'
) t ON t.ID = q.ID
ORDER BY q.CREATE_DATE DESC LIMIT 10;

SELECT '=== C. count: 현재 (= 제안과 동일, 변경 없음) ===' AS marker;
EXPLAIN
SELECT COUNT(*) FROM (
  SELECT q2.ID FROM QUESTION q2
   WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
  UNION
  SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID
   WHERE u1.USERNAME LIKE '%자바%'
  UNION
  SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID
   WHERE u2.USERNAME LIKE '%자바%'
) t;

SELECT '=== D. 결과 동일성: 두 쿼리의 ID 집합 비교 (0이면 동일) ===' AS marker;
SELECT
  (SELECT COUNT(*) FROM QUESTION q WHERE q.ID IN (
     SELECT q2.ID FROM QUESTION q2 WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
     UNION SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID WHERE u1.USERNAME LIKE '%자바%'
     UNION SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID WHERE u2.USERNAME LIKE '%자바%'
   )) AS cnt_in,
  (SELECT COUNT(*) FROM QUESTION q JOIN (
     SELECT q2.ID AS ID FROM QUESTION q2 WHERE MATCH(q2.SUBJECT, q2.CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
     UNION SELECT q3.ID FROM QUESTION q3 JOIN SITE_USER u1 ON q3.AUTHOR_ID = u1.ID WHERE u1.USERNAME LIKE '%자바%'
     UNION SELECT a.QUESTION_ID FROM ANSWER a JOIN SITE_USER u2 ON a.AUTHOR_ID = u2.ID WHERE u2.USERNAME LIKE '%자바%'
   ) t ON t.ID = q.ID) AS cnt_join;
