-- scenario-a.js가 사용하는 키워드별 FULLTEXT 매칭 건수
SELECT '자바' AS kw, COUNT(*) AS ft_match FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('자바' IN BOOLEAN MODE)
UNION ALL SELECT '스프링', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('스프링' IN BOOLEAN MODE)
UNION ALL SELECT 'JPA', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('JPA' IN BOOLEAN MODE)
UNION ALL SELECT '쿼리', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('쿼리' IN BOOLEAN MODE)
UNION ALL SELECT '오류', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('오류' IN BOOLEAN MODE)
UNION ALL SELECT '성능', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('성능' IN BOOLEAN MODE)
UNION ALL SELECT '테스트', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('테스트' IN BOOLEAN MODE)
UNION ALL SELECT '질문', COUNT(*) FROM QUESTION WHERE MATCH(SUBJECT, CONTENT) AGAINST ('질문' IN BOOLEAN MODE);
